### ISSUE TITLE
How to achieve custom size for a component

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-docfx#4022]
## Description  
The [Size topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/display-density) explains how to choose one of the three predefined sizes:

The available values for --ig-size are --ig-size-small, --ig-size-medium, and --ig-size-large.

Still, the documentation does not say anything about how to achieve a custom size, which I believe is a common 80% scenario. Please update documentation with proper examples.

**Comment by hanastasov** [comment]
The doc has this example:

![image](https://github.com/IgniteUI/igniteui-docfx/assets/14248932/e404a3ba-4ba2-4c66-9742-ef7e2d2316e1)

Which I perceive as a bit misleading - because it says how to make a component react to changes in --ig-size and the syntax with sizable is not that popular. In my opinion the doc should have the most basic example how to set a custom size for a component, i.e.:

```scss
.my-elem {
    --size: #{rem(28px)};
    font-size: #{12px};
    font-weight: #{24px};
}
```

**Comment by simeonoff** [comment]
For the avatar component there's the `--size` and `--igx-avatar-size` variables. Used based on context.

They can be used in the following ways:

```html
<div class="my-app">
  <igx-avatar></igx-avatar>
</div>
```

```scss
// You can use the shorthand version when targeting the `igx-avatar` directly.
igx-avatar {
  --size: 200px;
}

// Or the universal avatar size variable to target all instances.
.my-app {
  --igx-avatar-size: 200px;
}
```
